### PR TITLE
Moved content from template to hugo style content

### PR DESCRIPTION
**Pull request by rac2030**
Removed sample pictures from deployed template and into demo site.
Replaced inline content in template with hugo style markdown rendering
keeping the same output to index.html

### CODE REVIEW

**Comment by rac2030** [comment]
I used your template in a site I'm building so I committed back the changes I made locally ;-)

**Comment by sethmacleod** [comment]
Hi @rac2030 

I'm having trouble getting your changes to work. Clicking on the tabs treats them as links instead of a modal. And they 404 too. Is it working on your end? I'd love to merge your work.

**Comment by rac2030** [comment]
hmmmm.... you are right, have to take a closer look why it renders the index empty but without any error message...
I tough I copy pasted all the relevant changes but seems I made a mistake somewhere or missing something, my bad.
Try to fix this and commit ASAP.
Sample output from my project (without much content as the texts are work in progress and thus not yet public) is at https://robinson-schule.ch/

**Comment by rac2030** [comment]
This time it is properly tested in a fresh hugo site ;-)
Please try again and tell me if it still has issues.

I also simplyfied some things and converted html examples from the original html5up template to the elements markdown.

The issue was that menu needs to be set from the config.toml as we don't render single pages and while they get added to the menu object it somehow seems it then does not render index.html.
No clue why exactly but with the menu in config it is working properly.
Also added sitemap.xml generation with proper links parsed from menu for the google indexer.

**Comment by rac2030** [comment]
Please note that I haven't updated the README but there are some changes in there.
I moved the sample pictures into the sample site (no need to have them if not used) and index.html does not need to be touched anymore.

All should be hugo new site blabla and then hugo new intro.md ...
And Menu config in the config.toml

**Comment by sethmacleod** [comment]
You are a hero!

It's working for me now. Before I merge, I wanted to get your opinion on best practices for the site menu. The main menu does work either with the config.toml or with the front matter. If we were to use the front matter method, we could edit the default archetype to have something like:

    +++
    title = ""
    id = ""
    [menu.main]
    url = ""
    weight = 
    +++

I don't have any strong feelings either way.

**Comment by rac2030** [comment]
That was the original plan, let the content decide and use it in front matter but somehow it is not working. If you can get it to work would be perfect of course to have both options as in standard hugo usage.
Maybe it has to do with that the md files not getting rendered into single pages but we just aggregate them in index.html into div's to have that single page feeling.

Ideally I wanted to get rid of menu config but that seems to be not easy possible without hugo allowing for preprocessors. then we could generate the id from the filename (I wanted to avoid using title as it may have spaces and other stuff in it) and the url is given by #id to the base url so it would only need weight.

Now to the best practices and opinion part...
Doing it in front matter for such a limited set of pages, I see nothing against it. On larger pages It can cause confusion and it may be easier to maintain when having the menu in a config.

**Comment by rac2030** [comment]
Ok I just tested something and it works either way

**Comment by rac2030** [comment]
As an example for the about.md
```
+++
title = "About"
id = "about"
[menu.main]
url = "#about"
weight = -10
name = "About"
+++
```

With that we can remove it from the config and put it into the archetype

**Comment by rac2030** [comment]
I don't like the duplication but AFAIK the preprocessor discussion or ticket is still open and nobody has implemented it yet in hugo. This would be a good case to reduce the duplicate code and add a hook for getting default values in case nothing is configured.

We may just get around the id parameter when we have the url parameter and just strip the #-tag in index.html template where we loop trough all the pages.

**Comment by rac2030** [comment]
That could be done in onepagestyle.html default layout

**Comment by sethmacleod** [comment]
Have you seen how the [Academic Theme](https://github.com/gcushen/hugo-academic) handles this?

**Comment by rac2030** [comment]
In that case, as a template should be robust, some null checks should be added and if url is not set it looks if id is set.
This would allow both possible usages.
Need to get up for work now ;-)

**Comment by rac2030** [comment]
Looks good, shouldn't the menu.main and URL be part of the archetype as well?

Looking at code from mobile so I might missed a commit

**Comment by sethmacleod** [comment]
We don't need menu.main or the URL in the front matter since we are using the base file name in the html for the URL.

    {{ range .Data.Pages }}
    <li><a href="#{{ .File.BaseFileName }}">{{ .Title }}</a></li>
    {{ end }}

I got the idea from the Academic Theme. It's currently working on my computer. Let me know if it works on yours when you get a chance. *Fingers crossed*

**Comment by rac2030** [comment]
Cool I take a look in the evening of I get time or tomorrow

Am 28.02.2017 08:33 schrieb "sethmacleod" <notifications@github.com>:

**Comment by rac2030** [comment]
Cool I tested it shortly with my demo site and looks like its working fine.
;-)

**Comment by sethmacleod** [comment]
I updated the README to reflect our changes. Thanks so much for the help! Now it's a proper Hugo Theme!

:tada:

**Pull request merged**
